# Generated by Django 3.2.13 on 2022-06-01 06:49

import django.utils.timezone
import model_utils.fields
import opaque_keys.edx.django.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersistentCourseGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('user_id', models.IntegerField(db_index=True)),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(max_length=255)),
                ('percent_grade', models.FloatField()),
                ('letter_grade', models.CharField(max_length=255, verbose_name='Letter grade for course')),
                ('passed_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Date learner earned a passing grade')),
            ],
            options={
                'unique_together': {('course_id', 'user_id')},
                'index_together': {('passed_timestamp', 'course_id'), ('modified', 'course_id')},
            },
        ),
    ]
