# Generated by Django 3.2.15 on 2022-09-07 08:16

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learner_pathway_progress', '0003_auto_20220901_0616'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerEnterprisePathwayMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('enterprise_customer_uuid', models.UUIDField(db_index=True, editable=False, help_text='UUID of associated enterprise customer', verbose_name='ENTERPRISE_CUSTOMER_UUID')),
                ('learner_pathway_uuid', models.UUIDField(editable=False, help_text='UUID of associated pathway', verbose_name='LEARNER_PATHWAY_UUID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'learner_pathway_uuid', 'enterprise_customer_uuid')},
            },
        ),
        migrations.DeleteModel(
            name='LearnerPathwayMembership',
        ),
    ]
