# Generated by Django 3.2.15 on 2022-10-07 12:58

from django.db import migrations


def apply(apps, schema_editor):
    LearnerPathwayMembership = apps.get_model('learner_pathway_progress', 'LearnerEnterprisePathwayMembership')
    for pathway_membership in LearnerPathwayMembership.objects.all().iterator(chunk_size=100):
        pathway_membership.delete()

    LearnerPathwayProgress = apps.get_model('learner_pathway_progress', 'LearnerPathwayProgress')
    for pathway_progress in LearnerPathwayProgress.objects.all().iterator(chunk_size=100):
        pathway_progress.delete()

def revert(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('learner_pathway_progress', '0004_auto_20220907_0316'),
    ]

    operations = [
        migrations.RunPython(apply, revert),
    ]
