# Generated by Django 3.2.15 on 2023-12-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner_pathway_progress', '0006_auto_20231228_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(auto_now=True, default='Died'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_death',
            field=models.DateField(blank=True, default='Died'),
        ),
    ]
